game: 'hex'

training:
    'num_games': 15
    'num_search_games_limit': 10
    'rollout_time_limit': 2
    'save': True
    'num_saves': 5
    'alternate_players': True
    'starting_player': 1
    'epsilon': .99
    'epsilon_decay': .99
    'target_epsilon': .01
    'c': 1
    'rbuf_cap': 32
    'minibatch_size': 32

nim:
    'max_removal': 3
    'num_stones': 15
    actor:
        'learning_rate': .0001
        'layers': [15, 3]
        'optimizer': 'adam'
        'activation_fn': 'relu'
        'output_activation': 'softmax'
        'loss_fn': 'cross_entropy'
    
hex:
    'board_size': 4
    'display': False
    actor:
        'learning_rate': 0.0001
        'layers': [100, 200, 100, 25, 16]
        'optimizer': 'rmsprop'
        'activation_fn': 'tanh'
        'output_activation': 'softmax'
        'loss_fn': 'cross_entropy'

topp:
    'M': 5
    'num_games': 25
    game:
        'board_size': 5
        'display': False

    
graph:
    'pause': True
    'update_freq': .001
    'pause_on_win': True